hmcts/div-shared-infrastructure

- main.tf
As instructed by https://tools.hmcts.net/confluence/display/CNP/Governance+and+Tagging
> Set resource group tags

- Jenkinsfile_CNP
- application-insights.tf
- asp.tf
- main.tf
- variables.tf
Set common tags to all resources
> DIV-3600 - Set tags common-tags on resource group/app service plan

- Jenkinsfile_CNP
- alerts.tf
DIV-3956 
Because integration tests cause a lot of 400/422 errors
```
[ ] Yes
[x] No
```
> DIV-3956 - only enable bad requests alert in prod

- aat.tfvars
- asp.tf
- variables.tf
I am manually deleting the split shared ASP resources. This PR will stop them from automatically being created. Since div-aat already exists as an ASP, this change will not overwrite it / provision a new one.
> Use one asp with I3 size

- Jenkinsfile_CNP
- aat.tfvars
- app-gateway.tf
- prod.tfvars
- sandbox.tfvars
- variables.tf
Enables listeners for Decree Absolute.
> Add In Decree Absolute Listeners

- aat.tfvars
- alerts.tf
- app-gateway.tf
- ithc.tfvars
- prod.tfvars
- sandbox.tfvars
- variables.tf
DIV-5117
Update ITHC with the latest master code + set the external hostname/cert name for ITHC
```
[ ] Yes
[ ] No
```
> DIV-5117 - Update ITHC with master

- Jenkinsfile_CNP
New Jenkinsfile for pipeline requires as per #cloud-native channel
> Apply new format for Jenkins build

- app-gateway.tf
- asp.tf
- palo-alto.tf
DIV-5762
* disabled app service plan as we've migrated to AKS
* force detection mode for WAF until firewall issues are resolved (it's already in detection mode manually..)
```
[ ] Yes
[x] No
```
> DIV-5762 - disabled app service plan creation and put WAF in detection

- .gitignore
- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- aat.tfvars
- alerts.tf
- app-gateway.tf
- asp.tf
- ithc.tfvars
- key-vault.tf
- palo-alto.tf
- perftest.tfvars
- prod.tfvars
- sandbox.tfvars
- variables.tf
DIV-5844
Merge master into ITHC to allow ITHC testing for xui
```
[ ] Yes
[ ] No
```
> DIV-5844 - Update ithc

- alerts.tf
> Adding alert to notify us if data extraction stops sending e-mails

- demo.tfvars
Adding terraform variables for the demo environment.
```
[ ] Yes
[ X ] No
```
> Adding terraform variables for the demo environment

- alerts.tf
**Please do not merge this until the whole feature is switched on in PROD.**
```
[ ] Yes
[ x ] No
```
> DIV-6441: Creating alert for AOS Overdue job

- key-vault.tf
- perftest.tfvars
- variables.tf
https://tools.hmcts.net/jira/browse/RPET-460
Changed product_group_object_id to equal id for dcd_divorce to allow keys to be added to perftest 
```
[ ] Yes
[x] No
```
> RPET-460-Perftest

- action-groups.tf
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> TA-471: Add new action group

- action-groups.tf
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> TA-471: Fix action groups

- alerts.tf
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> TA-471: Test alerts with new email group

- state.tf
https://tools.hmcts.net/jira/browse/DTSSE-526
```
[ ] Yes
[ ] No
```
> Add azuread provider Update state.tf

- aat.tfvars
DTSPO-6373
Update variable for new manually created MI.
```
[ ] Yes
[x] No
```
> Update div-aat-mi object ID

- state.tf
https://tools.hmcts.net/jira/browse/DTSSE-2906
> update azurerm to 3.40 per slack nag

- main.tf
https://tools.hmcts.net/jira/browse/DFR-1999
> DFR-1999 shared redis for front end

- .github/renovate.json
- application-insights.tf
https://tools.hmcts.net/jira/browse/DFR-2320
> DFR-2320 adding appinsights secret to divorce

- aat.tfvars
- demo.tfvars
- ithc.tfvars
- key-vault.tf
- perftest.tfvars
- prod.tfvars
- sandbox.tfvars
- variables.tf
Removes mention of old MI
New ones added in https://github.com/hmcts/div-shared-infrastructure/commit/8ffc59ba7ba6f7e4897b6dba6cf58b7ef3f5767a
> Update to remove old MI mentions

- application-insights.tf
https://tools.hmcts.net/jira/browse/DTSPO-16745
Re-running this pipeline to deploy alert rules and action group from this module terraform-module-application-insights
it will also allow us to send slack notification to specific slack for this team.
> DTSPO-16745 running it to send slack notification
